// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qturwiorzsfnzdvewlhl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF0dXJ3aW9yenNmbnpkdmV3bGhsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNDAxNDcsImV4cCI6MjA2MzkxNjE0N30.dCpft3GNHLTCaRj8MLgVhWeTM5x9gvI5uv4O7kvxjxk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);